### ISSUE TITLE
Missing left arrow in V1.4 ?

### ISSUE THREAD

**Issue by 3ERL1N** [trepmal/mini-loops#7]
Hi Kailey,
I am not sure, but I guess there is a little issue in V1.4 of mini-loops. 
Before each ul-list item is a link shown as a text beginning with "a href ..." (without quotes). 
I guess a "<" in front of "a href" is missing to switch the text to HTML-code. 
Sorry aboot my English. :)
Best regards, Tobi

**Comment by trepmal** [comment]
Hi,

If you are using the widget, can you share what the item formats look like?
If you are using the shortcode, can you share your code?

![Screen Shot 2021-06-15 at 9 29 48 PM](https://user-images.githubusercontent.com/251183/122158064-d7d0e900-ce20-11eb-9f25-8504890030d9.png)
![Screen Shot 2021-06-15 at 9 29 40 PM](https://user-images.githubusercontent.com/251183/122158065-d9021600-ce20-11eb-8df2-c33e0fcb5978.png)

It's possible something needs to be re-saved after the update.

**Comment by 3ERL1N** [comment]
Hi Kailey,

 

thanks for your fast reply! :)

 

I don’t use the widgets, only the shortcode itself. This is, how a text segment with a title looks …

 



 

And this is how my text-block at the frontend / website looks in V1.4 …

 



 

It works fine in Version 1.3.1.

 

Do you have any idea about the reason? 

 

Best regards, 

 

Tobi 

 

 

 

Von: Kailey Lampert ***@***.*** 
Gesendet: Mittwoch, 16. Juni 2021 06:33
An: trepmal/mini-loops ***@***.***>
Cc: 3ERL1N ***@***.***>; Author ***@***.***>
Betreff: Re: [trepmal/mini-loops] Missing left arrow in V1.4 ? (#7)

 

Hi,

If you are using the widget, can you share what the item formats look like?
If you are using the shortcode, can you share your code?

 <https://user-images.githubusercontent.com/251183/122158064-d7d0e900-ce20-11eb-9f25-8504890030d9.png> 
 <https://user-images.githubusercontent.com/251183/122158065-d9021600-ce20-11eb-8df2-c33e0fcb5978.png> 

It's possible something needs to be re-saved after the update.

**Comment by trepmal** [comment]
Can you try sending that again? Might need to do so directly in GitHub, looks like the shortocde got removed in the email reply

**Comment by 3ERL1N** [comment]
Oh, sorry, my fault ... I didn't check the mail result online ... 

My code ...
![1](https://user-images.githubusercontent.com/85971515/122297026-644fda00-cefb-11eb-939f-a675cf4a45d0.jpg)

Result on my page ...
![2](https://user-images.githubusercontent.com/85971515/122297024-63b74380-cefb-11eb-9ae5-36763e694376.jpg)

**Comment by trepmal** [comment]
Thanks, I'm able to replicate it now, so I will look into it!

**Comment by 3ERL1N** [comment]
Hi Kailey, 

your replies are incredible quick. If you would sit in a car, this would be speeding for sure. :)

Thanks a lot for your reply, please take your time. 1.3.1 works great for me. 

 

Have a nice afternoon.

 

Best regards all the way from Berlin,

 

Tobi 







 

Von: Kailey Lampert ***@***.*** 
Gesendet: Mittwoch, 16. Juni 2021 23:39
An: trepmal/mini-loops ***@***.***>
Cc: 3ERL1N ***@***.***>; Author ***@***.***>
Betreff: Re: [trepmal/mini-loops] Missing left arrow in V1.4 ? (#7)

 

Thanks, I'm able to replicate it now, so I will look into it!

**Comment by trepmal** [comment]
1.4.1 is now released, please let me know if it doesn't fix it the problem for you

**Comment by 3ERL1N** [comment]
Thank you very much - it works like a charme! I am very happy with the result. #VielenDank 

Best regards, Tobi
